#ifndef GUARD_CONSTANTS_OUTFITS_H
#define GUARD_CONSTANTS_OUTFITS_H

//! outfits lists
#define OUTFIT_USUAL_GREEN 0
#define OUTFIT_UNUSUAL_RED 1
#define OUTFIT_COUNT 2

#define OUTFIT_BEGIN OUTFIT_USUAL_GREEN
#define OUTFIT_END   OUTFIT_UNUSUAL_RED

#define DEFAULT_OUTFIT OUTFIT_USUAL_GREEN

#endif //! GUARD_CONSTANTS_OUTFITS_H
