name: CI

on:
  push:
    branches:
      - dev
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm
    env:
      GAME_VERS: FIREFLOWER
      GAME_REVISION: 0
      GAME_LANG: ENG
      MODERN: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install binutils
        run: sudo apt install -y build-essential libpng-dev libelf-dev golang-go
        # build-essential, git, and libpng-dev are already installed
        # gcc-arm-none-eabi is only needed for the modern build
        # as an alternative to dkP

      - name: Install poryscript
        run: |
          git clone https://github.com/huderlem/poryscript.git tools/poryscript
          cd tools/poryscript
          go build
          cd ../../

      - name: FireFlower
        env:
          GAME_VERS: FIREFLOWER
        run: make -j${nproc} -O all

      - name: SuperLeaf Indonesian
        env:
          GAME_VERS: SUPERLEAF
          GAME_LANG: INA
        run: make -j${nproc} -O all
