name: CI

on:
  push:
    branches:
      - dev
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GAME_VERSION: EMERALD
      GAME_REVISION: 0
      GAME_LANGUAGE: ENGLISH
      MODERN: 1
      COMPARE: 0
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install binutils
        run: sudo apt install gcc-arm-none-eabi binutils-arm-none-eabi libelf-dev g++ golang-go
        # build-essential, git, and libpng-dev are already installed
        # gcc-arm-none-eabi is only needed for the modern build
        # as an alternative to dkP

      - name: Install poryscript
        run: |
          git clone https://github.com/huderlem/poryscript.git tools/poryscript
          cd tools/poryscript
          go build
          cd ../../

      - name: Modern
        run: make -j${nproc} -O all
