name: CI

on:
  push:
    branches:
      - dev
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm
    env:
      GAME_VERSION: EMERALD
      GAME_REVISION: 0
      GAME_LANGUAGE: ENGLISH
      MODERN: 0
      COMPARE: 0
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout agbcc
        uses: actions/checkout@v2
        with:
          path: agbcc
          repository: pret/agbcc

      - name: Checkout poryscript
        uses: actions/checkout@v2
        with:
          path: poryscript
          repository: huderlem/poryscript

      - name: Install binutils
        run: sudo apt install -y build-essential libpng-dev libelf-dev golang-go
        # build-essential, git, and libpng-dev are already installed
        # gcc-arm-none-eabi is only needed for the modern build
        # as an alternative to dkP

      - name: Install agbcc
        run: |
          ./build.sh
          ./install.sh ../
        working-directory: agbcc

      - name: Install poryscript
        run: |
          go build
          ./install.sh ../
        working-directory: poryscript

      - name: Agbcc
        env:
          MODERN: 0
          COMPARE: 0
        run: make -j${nproc} -O all

      - name: Modern
        env:
          MODERN: 1
          COMPARE: 0
        run: make -j${nproc} -O all
